version: '3'

# This docker-compose is for running tests

services:

  # For running the Flask server
  web:
    build:
      context: .
      args:
        DEVELOPMENT: 1
    ports:
      - 5000:5000
    volumes:
      - ${PWD}:/kb/module
